import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { Header } from "./ui/Header";
import { Footer } from "./ui/Footer";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en w-full h-full">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="flex flex-col">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
